force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Number_of_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Assignments__c</fullName>
    <label>Number of Assignments</label>
    <summaryForeignKey>Resource_Assignment__c.Schedule__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Number_of_Work_Orders_in_Week__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Work_Orders_in_Week__c</fullName>
    <formula>Week__r.Number_of_Work_Orders__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Work Orders in Week</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Total_Fine__c + Total_Labour_Cost__c +  Total_Fine_Unfinished_Work_Orders__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Fine__c.field-meta.xml
<CustomField>
    <fullName>Total_Fine__c</fullName>
    <label>Total Fine Late Work Orders</label>
    <summarizedField>Resource_Assignment__c.Fine_Shadow__c</summarizedField>
    <summaryForeignKey>Resource_Assignment__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Fine_Unfinished_Work_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Fine_Unfinished_Work_Orders__c</fullName>
    <formula>Week__r.Fine_per_unfinished_WO__c * (Number_of_Work_Orders_in_Week__c -  Number_of_Assignments__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fine Unfinished Work Orders</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Hours_spent_in_Overtime_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_spent_in_Overtime_Hours__c</fullName>
    <label>Total Hours spent in Overtime Hours</label>
    <summarizedField>Resource_Assignment__c.Number_of_Hours_Worked_in_Overtime__c</summarizedField>
    <summaryForeignKey>Resource_Assignment__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Hours_spent_in_Regular_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours_spent_in_Regular_Time__c</fullName>
    <label>Total Hours spent in Regular Time</label>
    <summarizedField>Resource_Assignment__c.Number_of_Hours_Worked_in_Regular_Time__c</summarizedField>
    <summaryForeignKey>Resource_Assignment__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Total_Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Labour_Cost__c</fullName>
    <label>Total Labour Cost</label>
    <summarizedField>Resource_Assignment__c.Cost__c</summarizedField>
    <summaryForeignKey>Resource_Assignment__c.Schedule__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <referenceTo>Week__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Week__c/Week__c.object-meta.xml
<CustomObject>
    <label>Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScheduleComparisonController.cls
/**
* @author Kyrylo Mazur
* @date 2024
*
* @group Schedule Visualization
* @group-content 
*
* @description Controller class for scheduleComparison LWC.
*/
public with sharing class ScheduleComparisonController {

    /**
    * @description Get data about schedules related to given week
    * @param weekId Id of the week record
    * @return list of schedules related to given week
    */
    @AuraEnabled
    public static List<Schedule__c> getSchedulesByWeek(Id weekId){
        return [SELECT Name, Number_of_Assignments__c, Number_of_Work_Orders_in_Week__c, Total_Cost__c, Total_Fine__c, Total_Fine_Unfinished_Work_Orders__c, Total_Hours_spent_in_Overtime_Hours__c, Total_Hours_spent_in_Regular_Time__c, Total_Labour_Cost__c
                FROM Schedule__c WHERE Week__c =: weekId WITH SECURITY_ENFORCED ORDER BY Name];
    }
}