force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/End_Regular_Working_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Regular_Working_Time__c</fullName>
    <defaultValue>&quot;17:00&quot;</defaultValue>
    <label>End Regular Working Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Overtime_Capable__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Capable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overtime Capable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Performance__c.field-meta.xml
<CustomField>
    <fullName>Performance__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Unit of works per hour</description>
    <label>Performance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Regular_Rate__c.field-meta.xml
<CustomField>
    <fullName>Regular_Rate__c</fullName>
    <label>Regular Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Start_Regular_Working_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Regular_Working_Time__c</fullName>
    <defaultValue>&quot;08:00&quot;</defaultValue>
    <label>Start Regular Working Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <referenceTo>Week__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource_Assignment__c/Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Resource Assignment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Assignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Assignments</relationshipLabel>
    <relationshipName>Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Assignment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Resource Assignments</relationshipLabel>
    <relationshipName>Resource_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Week__c/Week__c.object-meta.xml
<CustomObject>
    <label>Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Week__c/fields/Fine_per_unfinished_WO__c.field-meta.xml
<CustomField>
    <fullName>Fine_per_unfinished_WO__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Fine per unfinished WO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>Used to store information for work orders</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Amount_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Work__c</fullName>
    <description>In Unit of Works</description>
    <label>Amount of Work</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Fine_per_hour_delay__c.field-meta.xml
<CustomField>
    <fullName>Fine_per_hour_delay__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Fine per 1h delay of WO to be completed</description>
    <label>Fine per hour delay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <referenceTo>Week__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <description>time in hours</description>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SchedulerThree.cls
public class SchedulerThree extends Scheduler.AbstractScheduler {
    private List<Resource__c> resources = new List<Resource__c>();
    private Map<Id, DateTime> nextAvailableDate = new Map<Id, DateTime>();
    public SchedulerThree() {
        this.setName('SchedulerThree');
    }
 
    private static Integer calculateWoPriorityForWo(Work_Order__c wo, Integer average_resource_price) {
        //average_resource_price 50 ?
        return Integer.valueOf(wo.Fine_per_hour_delay__c * (24 - wo.End_Time__c.hour())
              + average_resource_price * (12 - wo.Amount_of_Work__c));
             
    }
 
    private static Decimal calculatePriorityForResource(Resource__c r) {
        return (r.Regular_Rate__c) / r.Performance__c;
    }
 
 
    private class WOWrapper implements Comparable{
        public Work_Order__c WorkOrder;
 
        public WOWrapper(Work_Order__c wo) {
            WorkOrder = wo;
        }
 
        public Integer compareTo(Object second_wrapper) {
            return 1 * (
                             calculateWoPriorityForWo(this.WorkOrder,80)
                           - calculateWoPriorityForWo(((WOWrapper)second_wrapper).WorkOrder, 80)
                        );
        }
    }
 
    private class ResourceWrapper implements Comparable{
        public Resource__c Resource;
        public Set<Integer> UsedHours;
        public Week__C Week;
 
        public ResourceWrapper(Resource__c res, Week__c w) {
            Resource = res;
            UsedHours = new Set<Integer>();
            for(Integer i = 0; i < 24; i++) {
                UsedHours.add(i);
            }
            Week  = w;
        }
 
        public Integer compareTo(Object second_wrapper) {
            return  1 * Integer.valueOf((calculatePriorityForResource(Resource) - calculatePriorityForResource(((ResourceWrapper)second_wrapper).Resource)));
        }
 
        public List<Integer> canResourceDoWO(Work_Order__c wo) {
            Integer amount_of_hours_needed = Integer.valueOf(Math.ceil((0.0 + wo.Amount_of_Work__c) / resource.Performance__c));
             
            if (amount_of_hours_needed * Resource.Regular_Rate__c >= Integer.valueOf(wo.Fine_per_hour_delay__c * (24 - wo.End_Time__c.hour()))) {
                //nothing to do here
                return null;
            }
            Integer start_hour = Math.max(Integer.valueOf(Resource.Start_Regular_Working_Time__c.substring(0,2)), wo.Start_Time__c.hour());
            Integer end_hour = Integer.valueOf(Resource.End_Regular_Working_Time__c.substring(0,2));
            for(Integer i = start_hour; i < end_hour - amount_of_hours_needed ; i++) {
                List<Integer> subset = new List<Integer>();
                for(Integer j = i; j < i + amount_of_hours_needed; j++) {
                    subset.add(j);
                }
                if (UsedHours.containsAll(subset)) {
                    UsedHours.removeAll(subset);
                    return subset;
                }
            }
            if (Resource.Overtime_Capable__c) {
                start_hour = wo.Start_Time__c.hour();
                for(Integer i = start_hour; i < 24 - amount_of_hours_needed; i++) {
                    List<Integer> subset = new List<Integer>();
                    for(Integer j = i; j < i + amount_of_hours_needed; j++) {
                        subset.add(j);
                    }
                    if (UsedHours.containsAll(subset)) {
                    //
                    //big fine
                        if (subset.get(subset.size()-1) > wo.End_Time__c.hour()) {
                            Integer fee_time = subset.get(subset.size()-1) - wo.End_Time__c.hour();
                            //overtime here - check how big is the fee
                            if (amount_of_hours_needed * Resource.Regular_Rate__c + fee_time*wo.Fine_per_hour_delay__c
                                 >= Integer.valueOf(week.Fine_per_unfinished_WO__c)) {
                                //nothing to do here
                                return null;
                            }
                        }
 
                        UsedHours.removeAll(subset);
                        return subset;
                    }
                }
            }
            return null;
        }
    }
 
 
    public override virtual List<Resource_Assignment__c> callImplementation(List<Work_Order__c> workOrders, List<Resource__c> resources) {
        Map<Date, List<WOWrapper> > work_orders_by_dates = new Map<Date, List<WOWrapper>>();
 
        for(Work_Order__c wo : workOrders) {
            Date d = wo.Start_Time__c.date();
            if (!work_orders_by_dates.containsKey(d)) {
                work_orders_by_dates.put(d, new List<WOWrapper>());
            }
            work_orders_by_dates.get(d).add(new WOWrapper(wo));
        }
        List<Resource_Assignment__c> assignments = new List<Resource_Assignment__c>();
        for (Date d : work_orders_by_dates.keySet()) {
            //get best resources for every day
            List<ResourceWrapper> resources_by_priority = new List<ResourceWrapper>();
            for(Resource__c r : resources) {
                resources_by_priority.add(new ResourceWrapper(r, week));
            }
            resources_by_priority.sort();
 
            List<WOWrapper> workorders_for_today = work_orders_by_dates.get(d);
            workorders_for_today.sort();
            for(WOWrapper wo : workorders_for_today) {
                for(Integer i = 0; i < resources_by_priority.size(); i++) {
                    List<Integer> res = (resources_by_priority.get(i)).canResourceDoWO(wo.WorkOrder);
                    if (res != null) {
                        //system.debug(LoggingLevel.Error, 'RETURNED' + res);
                        //System.debug(LoggingLevel.Error, 'LEFT' + resources_by_priority.get(i).UsedHours);
 
                        Resource_Assignment__c ra = new Resource_Assignment__c();
                        ra.Work_Order__c  = wo.WorkOrder.Id;
                        ra.Resource__c = resources_by_priority.get(i).Resource.Id;
                         
                        if(res.size() == 0) {
                            ra.Start_Time__c = wo.WorkOrder.Start_Time__c;
                            ra.End_Time__c = ra.Start_Time__c;//0 hours -- amazing
                        } else {
                        ra.Start_Time__c = DateTime.newInstance(d, Time.newInstance(res.get(0),0,0,0));
                        ra.End_Time__c = ra.Start_Time__c.addMinutes(Integer.valueOf(
                                                                        Math.floor(60*(0.0 +  wo.WorkOrder.Amount_of_Work__c)
                                                                            / resources_by_priority.get(i).Resource.Performance__c
                                                                            )
                                                                                     )
                                                                     );
                        }
                        assignments.add(ra);
                        break;
                    }
                }
            }
        }
 
        return assignments;
    }
 
}