force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/End_Regular_Working_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Regular_Working_Time__c</fullName>
    <defaultValue>&quot;17:00&quot;</defaultValue>
    <label>End Regular Working Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Overtime_Capable__c.field-meta.xml
<CustomField>
    <fullName>Overtime_Capable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Overtime Capable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Performance__c.field-meta.xml
<CustomField>
    <fullName>Performance__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Unit of works per hour</description>
    <label>Performance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Start_Regular_Working_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Regular_Working_Time__c</fullName>
    <defaultValue>&quot;08:00&quot;</defaultValue>
    <label>Start Regular Working Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource_Assignment__c/Resource_Assignment__c.object-meta.xml
<CustomObject>
    <label>Resource Assignment</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource_Assignment__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Resource Assignments</relationshipLabel>
    <relationshipName>Resource_Assignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource_Assignment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Resource Assignments</relationshipLabel>
    <relationshipName>Resource_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>Used to store information for work orders</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{000000}</displayFormat>
        <label>Work Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Amount_of_Work__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Work__c</fullName>
    <description>In Unit of Works</description>
    <label>Amount of Work</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <description>time in hours</description>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SchedulerOne.cls
public class SchedulerOne extends Scheduler.AbstractScheduler {
    private List<Resource__c> resources = new List<Resource__c>();
    private Map<Id, DateTime> nextAvailableDate = new Map<Id, DateTime>();
    // Wrapper for sorting
    public class WOWrapper implements Comparable {
        public Work_Order__c wo;
        public WOWrapper(Work_Order__c wo) {
            this.wo = wo;
        }
        public Integer compareTo(Object compareTo) {
            WOWrapper compareToWo = (WOWrapper) compareTo;
            Integer returnValue = 0;
            if (wo.Start_Time__c > compareToWo.wo.Start_Time__c) {
                returnValue = 1;
            } else if (wo.Start_Time__c < compareToWo.wo.Start_Time__c) {
                returnValue = -1;
            }
            return returnValue;      
        }
    }
    public SchedulerOne() {
        this.setName('SchedulerOne');
    }
  public override virtual List<Resource_Assignment__c> callImplementation(List<Work_Order__c> workOrders, List<Resource__c> resources) {
        // Sorting
        List<WOWrapper> woWrapperList = new List<WOWrapper>();
        for (Work_Order__c wo : workOrders) {
            woWrapperList.add(new WOWrapper(wo));
        }
        woWrapperList.sort();
         
        List<Resource_Assignment__c> assignments = new List<Resource_Assignment__c>();
        this.resources = resources;
        this.fillEarliestAvailableDates(workOrders);
        for (WOWrapper wrapper : woWrapperList) {
            Resource_Assignment__c ra = this.getResourceAssignmentForWorkOrder(wrapper.wo);
            if (ra != null) {
                assignments.add(ra);
            }
        }
        Map<Id, List<Resource_Assignment__c>> assignmentsByResource = new Map<Id, List<Resource_Assignment__c>>();
        for (Resource_Assignment__c ra : assignments) {
            List<Resource_Assignment__c> ras = assignmentsByResource.get(ra.Resource__c);
            if (ras == null) {
                ras = new List<Resource_Assignment__c>();
            }
            ras.add(ra);
            assignmentsByResource.put(ra.Resource__c, ras);
        }
        //throw new Scheduler.SchedulerException('Assignments: ' + JSON.serializePretty(assignmentsByResource));
        return assignments;
    }
    private Resource_Assignment__c getResourceAssignmentForWorkOrder(Work_Order__c wo) {
         // Assign a random resource
        for (Resource__c r : this.resources) {
            DateTime earliestDate = this.nextAvailableDate.get(r.Id);
            if (earliestDate <= wo.Start_Time__c) {
                Boolean assign = false;
                if (Integer.valueOf(r.Start_Regular_Working_Time__c.substring(0,2)) > wo.Start_Time__c.hour() && Integer.valueOf(r.End_Regular_Working_Time__c.substring(0,2)) < wo.End_Time__c.hour()) {
                    assign = true;
                } else {
                    if (r.Overtime_Capable__c == true) {
                        assign = true;
                    }
                }
                if (assign == true) {
                    Resource_Assignment__c ra = new Resource_Assignment__c(Work_Order__c = wo.Id, Resource__c = r.Id, 
                                                                           Start_Time__c = wo.Start_Time__c, 
                                                                           End_Time__c = this.getEndTime(wo, r, wo.Start_Time__c));
                    if (ra.End_Time__c < this.week.Week_End__c) {
                        this.nextAvailableDate.put(r.id, ra.End_Time__c);
                        return ra;
                    }
                }
            }
        }
        return null;
    }
    private void fillEarliestAvailableDates(List<Work_Order__c> workOrders) {
        DateTime earliest = this.getEarliestDateTime(workOrders);
        for (Resource__c r : this.resources) {
            // As we don't respect overtime we are always available
            this.nextAvailableDate.put(r.Id, earliest);
        }
    }
    private DateTime getEarliestDateTime(List<Work_Order__c> woList) {
        DateTime earliestFound = DateTime.newInstance(2100, 1, 1, 1, 1, 1);
        for (Work_Order__c wo : woList) {
            if (wo.Start_Time__c < earliestFound) {
                earliestFound = wo.Start_Time__c;
            }
        }
        return earliestFound;
    }
    private DateTime getEndTime(Work_Order__c wo, Resource__c r, DateTime start) {
        return start.addMinutes((Integer) Math.ceil(this.getNumberOfHoursNeeded(wo, r) * 60));
    }
    private Decimal getNumberOfHoursNeeded(Work_Order__c wo, Resource__c r) {
        System.debug(LoggingLevel.ERROR, 'Amount of hours needed: ' + wo.Amount_of_Work__c + ' / ' + r.Performance__c + ' = ' + (wo.Amount_of_Work__c / r.Performance__c));
        return wo.Amount_of_Work__c / r.Performance__c;
    }
}